#!/usr/bin/env bash
# Factors Challenge

calculate_factor() {
    product=1
    for factor in $(factor "$1" | awk '{ for(i=2; i<=NF; i++) printf "%s ", $i }'); do
        ((product *= factor))
    done

    num1=$1
    num2=$product

    if ((num2 > num1)); then
        temp=$num1
        num1=$num2
        num2=$temp
    fi

    echo "$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
fi

while read -r line; do
    calculate_factor "$line"
done < "$1"
