#!/usr/bin/env bash
# RSA Challenge

calculate_factor() {
    product=1
    factor_count=0

    for factor in "$@"; do
        if [ $factor_count -gt 1 ]; then
            ((product *= factor))
        fi
        ((factor_count++))
    done

    num1=$2
    num2=$product

    if ((num2 > num1)); then
        temp=$num1
        num1=$num2
        num2=$temp
    fi

    echo "$1$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
fi

while read -r line; do
    calculate_factor $line
done < "$1"
